#include <stdio.h>
#include <ctype.h>

int main(int argc, char* argv[]) {
	char content[64], style[64], title[64];

	if (argv[1])
		for (unsigned int i = 0; i < sizeof(content); ++i)
			content[i] = argv[1][i];
	else {
    printf("Please provide a content file.\n");
		return 1;
	}

	if (argv[2])
		for (unsigned int i = 0; i < sizeof(style); ++i)
			style[i] = argv[2][i];
	else {
    printf("Please provide a stylesheet.\n");
		return 1;
	}

	if (argv[3])
		for (unsigned int i = 0; i < sizeof(title); ++i)
			title[i] = argv[3][i];
	else {
    printf("Please provide a title.\n");
		return 1;
	}

	FILE* html = fopen("index.html", "w");
	FILE* content_file = fopen(content, "r");

	char paragraph[1024];

	fprintf(html, "<!-- Code generated by Spenito's Simple HTML Generator -->\n");
	fprintf(html, "<!DOCTYPE html>\n");
	fprintf(html, "<html>\n");
	fprintf(html, "\t<head>\n");
	fprintf(html, "\t\t<title>%s</title>\n", title);
	if (style != NULL)
		fprintf(html, "\t\t<link rel='stylesheet' href='%s'>\n", style);
	fprintf(html, "\t</head>\n");
	fprintf(html, "\t<body>\n");
	fprintf(html, "\t\t<h1>%s</h1>\n", title);
	while (fgets(paragraph, sizeof(paragraph), content_file) != NULL)
		fprintf(html, "\t\t<p>%s</p>\n", paragraph);
	fprintf(html, "\t</body>\n");
	fprintf(html, "</html>");

	fclose(html);
	fclose(content_file);

	return 0;
}
